on:
  pull_request:
    types: [opened, edited]
jobs:
  linter:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
      contents: read
    steps:
    - uses: actions/checkout@v3
    - uses: smelly-python/smell-my-pr@main
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        command: pipenv run smelly-python -d src